fix: De-bump Npgsql.OpenTelemetry to work with LTS EntityFramework (#348)
## Which problem is this PR solving?

- error when using with EFCore `Encountered Exception of type
MethodAccessException: Attempt by method
'Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlRelationalConnection.get_CurrentAmbientTransaction()'
to access method 'Npgsql.NpgsqlConnection.get_Settings()' failed`

## Short description of the changes

- Similar to #298 there seem to be some issues with EntityFramework with
.NET 7. This reverts back to 6.0.7, but adds a bump to a later patch
version of 6.0.9.
- If this indeed solves the problem, a follow-up issue should be added
for separating out versions for .NET 6 and .NET 7. We don't currently
include net7.0 in this package so it doesn't make sense to add that
conditional block here.
- In the meantime, I added a dependabot ignore block so we don't
inadvertently update again; we can remove it once we update with
conditionals for .NET 7.